### ISSUE TITLE
How install 

### ISSUE THREAD

**Issue by slimako** [xaronnn/XaronBanner#1]
Hi, how fix this ?
http://screenshot.sh/m9g71r0eafDb2

**Comment by slimako** [comment]
Warning: file_get_contents(http/api.apixu.com/v1/current.json?key=''''&q=Stare Miasto): failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request in /hubert/index.php on line 74

Notice: date_default_timezone_set(): Timezone ID '' is invalid in /hubert/index.php on line 76

Warning: imagecreatefrompng(): Filename cannot be empty in /hubert/index.php on line 80

Warning: imagesx() expects parameter 1 to be resource, boolean given in /hubert/index.php on line 82

Warning: imagesy() expects parameter 1 to be resource, boolean given in /hubert/index.php on line 83

Warning: imagesx() expects parameter 1 to be resource, boolean given in /hubert/index.php on line 107

Warning: imagesy() expects parameter 1 to be resource, boolean given in /hubert/index.php on line 107

**Comment by xaronnn** [comment]
Insert "apixu.com" api key.
